/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-red": "#DC3535",
        "primary-orange": "#D17842",
        "primary-background-light": "#FFFFFF",
        "primary-background-dark": "#0C0F14",
        "secondary-background-light": "#F5F5F7",
        "secondary-background-dark": "#141921",
        "tertiary-background-light": "#E8E8E8",
        "tertiary-background-dark": "#21262E",
        "primary-grey-light": "#DADADA",
        "primary-grey-dark": "#252A32",
        "secondary-grey-light": "#C0C0C0",
        "secondary-grey-dark": "#2C3138",
        "primary-text-light": "#0C0F14",
        "primary-text-dark": "#FFFFFF",
        "secondary-text-light": "#52555A",
        "secondary-text-dark": "#AEAEAE",
        "tertiary-text-light": "#787878",
        "tertiary-text-dark": "#808080",
        "accent-text-light": "#A0A0A5",
        "accent-text-dark": "#52555A",
        "success-green": "#4BB543",
        "primary-overlay-light": "rgba(0,0,0,0.1)",
        "primary-overlay-dark": "rgba(12,15,20,0.5)",
        "secondary-overlay-light": "rgba(0,0,0,0.2)",
        "secondary-overlay-dark": "rgba(0,0,0,0.7)",
      },
      fontFamily: {
        "poppins-thin": ["Poppins-Thin", "sans-serif"],
        "poppins-extralight": ["Poppins-ExtraLight", "sans-serif"],
        "poppins-light": ["Poppins-Light", "sans-serif"],
        "poppins-regular": ["Poppins-Regular", "sans-serif"],
        "poppins-medium": ["Poppins-Medium", "sans-serif"],
        "poppins-semibold": ["Poppins-SemiBold", "sans-serif"],
        "poppins-bold": ["Poppins-Bold", "sans-serif"],
        "poppins-extrabold": ["Poppins-ExtraBold", "sans-serif"],
        "poppins-black": ["Poppins-Black", "sans-serif"],
      },
    },
  },
  plugins: [],
};
